name: nbnf
version: 1.0.0
github: "McEarl/nbnf"
license: GPL-3
author: "Marcel Schütz"
maintainer: "marcel.schuetz@fau.de"
copyright: "2024 Marcel Schütz"

extra-source-files:
- README.md
- LICENSE.md
- CHANGELOG.md

description: Please see the README on GitHub at <https://github.com/McEarl/nbnf#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - containers      # used for `Map`
  - parsec
  - hxt             # used for `hexStringToInt`
  - text
  - xml-conduit
  - html

executables:
  nbnf-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nbnf
    - text
    - pandoc
    - blaze-html
    - markdown

tests:
  forthel-syntax-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nbnf
    - ansi-terminal
